language: php
php:
  - "5.6"
cache:
  directories:
  - vendor
  - node_modules
addons:
  sauce_connect: true
before_install:
- nvm install 6.0.0

before_script:
- composer self-update
- composer global require hirak/prestissimo
- composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ `php-config --vernum` -ge 50400 ] && [ `php-config --vernum` -lt 70000 ]; then printf "yes\n" | pecl install -f apcu-4.0.10 ; fi"
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ `php-config --vernum` -ge 70000 ] ; then printf "yes\n" | pecl install -f apcu ; echo 'extension="apcu.so"' >> ./tests/apc.ini ; fi"
- sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != 'nightly' ] ; then phpenv config-add ./tests/apc.ini; fi"
- composer install -o --ignore-platform-reqs --prefer-dist
- npm i
- bin/console server:start
script:
- npm run test:remote
after_script:
- bin/console server:stop
env:
  matrix:
  - TEST_NAME="Sunrise PHP Travis"
notifications:
  hipchat:
    rooms:
      secure: S2g1T6N2gadmi+Dt3IjTkTrVRmPf0PG1pN5JXlB35RarQHs0GzBfhD1YT8Lm9keLc+XhM92rkEs7EyIrUtB+0x1O5A9bvPw0mDhtNhO6iPZDFajbZAPyA27vrA/JUMfEbigbuUkwxZggxYS5hnszDdvlwF97znwjT9G7fGZBU3+InxESq/Zt8g0AAqckQ434UlzsnyTmnUa6m8wU+zLEaTNJpF6XJ5DHDDiI7vv30Y7ZLWSLNOp8JVuGT9YEE1Q9CQ+UNvcDWYcr/B3Jr23b3NP5phDBg9T+mjJyflZyo/PClF1f3O+xIpTsx5xRApEmbCRafKIMJb46vTptaVdOf9GxCzGPC6/MKR6ngJGAyh1+jVPebJUTvSVW4QTkftC5XxjySDmBJ390ipZ9NT/+3zUIvSkZBH3597BJYqAJDdAj04jGobqPNOvab6Van8uEgjuhr/tL0qdfiehZIzOW0Kg7mj6b/HQlORMbMA/xbJrg190QmFt8KktSVhFhJ8J/YrxkepzaYbEOLKxpku9kpp4+J0sGXdI01T6mSTNeo6OFMFFiy327+3JJ4FuXAej8DH7T2bssn9LO4mAYhjGupnCjf4xSqN6/xg9tqGMq5UeHRh2JdwwnoMuhFp8j76tU/TPaKEA30+Ir9dfZgIz9hdOWpERvUyfUnXfc31FmsRo=
