imports:
  - { resource: 'parameters.yml' }
  - { resource: 'security.yml' }
  - { resource: 'services.yml' }
  - { resource: 'app.yml' }

parameters:
  locale: en
  handlebars.helper_interface.class: JaySDe\HandlebarsBundle\Helper\HelperInterface
  handlebars.helper_interface.method: handle

framework:
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  templating:
    engines: ['twig', 'handlebars']
  form: ~
  csrf_protection: { enabled: true }
  assets:
    base_path: /assets/
  default_locale: "%locale%"
  esi: { enabled: true }
  fragments: ~
  session:
    name: sunrise_session
    save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
  translator:
    paths:
    - "%kernel.root_dir%/../vendor/commercetools/sunrise-theme/translations"
twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
handlebars:
  cms:
    default_namespace: cms
  translation:
    default_namespace: main
    interpolation_prefix: __
    interpolation_suffix: __
  paths:
    - "%kernel.root_dir%/Resources/views"
    - "%kernel.root_dir%/../vendor/commercetools/sunrise-theme/templates"
commercetools:
  cache:
    category: true
    product_type: true
    product: true
  credentials:
    client_id: "%commercetools.client_id%"
    client_secret: "%commercetools.client_secret%"
    project: "%commercetools.project%"
  fallback_languages:
    de:
    - en
    en:
    - de
  currency:
    DE: EUR
    UK: GBP
assetic:
  debug: "%kernel.debug%"
  use_controller: "%kernel.debug%"
  filters:
    cssrewrite: ~
nelmio_security:
#    cookie_session:
#        enabled: true
    # signs/verifies all cookies
#    encrypted_cookie:
#        adapter: openssl
#        secret: def000002f118b5a5f130bdcda872ee1fa2e0a6dc797d760eb65f7baec5b06dc72f8647a54901754f44ebfdb1dfc0329546ed75614a1516f99eb66a9aa0880d8e6ca8cf7
#        names: ['*']
    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY
    # prevents redirections outside the website's domain
    external_redirects:
        abort: true
        log: true

    # prevents inline scripts, unsafe eval, external scripts/images/styles/frames, etc
    csp:
        report_logger_service: monolog.logger.security
        hosts: []
        content_types: []
        enforce:
            level1_fallback: true
            browser_adaptive: false
            report-uri: /nelmio/csp/report
            default-src:
                - 'self'
            font-src:
                - 'self'
                - fonts.googleapis.com
                - maxcdn.bootstrapcdn.com
                - fonts.gstatic.com
                - cdn.jsdelivr.net
            style-src:
                - 'self'
                - 'unsafe-inline'
                - fonts.googleapis.com
                - maxcdn.bootstrapcdn.com
                - ajax.googleapis.com
                - cdn.jsdelivr.net
                - cdnjs.cloudflare.com
            script-src:
                - 'self'
                - 'unsafe-inline'
                - cdnjs.cloudflare.com
                - maxcdn.bootstrapcdn.com
                - ajax.googleapis.com
                - cdn.jsdelivr.net
            img-src:
                - 'self'
                - 'unsafe-inline'
                - 'data:'
                - s3-eu-west-1.amazonaws.com
                - cdn.jsdelivr.net
            block-all-mixed-content: true # Default to false, blocks http content over https transport
            # upgrade-insecure-requests: true # Default to false, upgrades http requests to https transport

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # Forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # forced HTTPS handling, don't combine with flexible mode
    # and make sure you have SSL working on your site before enabling this
#    forced_ssl:
#        hsts_max_age: 2592000 # 30 days
#        hsts_subdomains: true

    # flexible HTTPS handling, read the detailed config info
    # and make sure you have SSL working on your site before enabling this
#    flexible_ssl:
#        cookie_name: auth
#        unsecured_logout: false
