security:
  providers:
    ctp:
      id: app.ctp_user_provider
#    in_memory:
#      memory:
#        users:
#          ylambers:
#            password: yaron
#            roles: 'ROLE_USER'
  access_control:
  - { path: user/secret, roles: ROLE_USER }
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Commercetools\Sunrise\AppBundle\Security\User\CTPUser: plaintext
  firewalls:
    main:
      anonymous: ~
      ctp-login:
        login_path: login_route
        check_path: login_check

      logout:
        path:   logout
        target: home
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    default:
      anonymous: ~